### ISSUE TITLE
Not support internal function redefined.

### ISSUE THREAD

**Issue by lancerhe** [badoo/soft-mocks#19]
When run phpunit with php 7.1 in macos:

> phpunit example-phpunit/ExampleTest.php --bootstrap example-phpunit/bootstrap.php
PHPUnit 5.7.5 by Sebastian Bergmann and contributors.

FFFFE                                                               5 / 5 (100%)

Time: 128 ms, Memory: 14.00MB

There was 1 error:

1) ExampleTest::testGenerator
TypeError: Argument 3 passed to QA\SoftMocks::redefineGenerator() must be an instance of Generator, instance of Closure given, called in /Users/lancer/Downloads/soft-mocks-master/example-phpunit/ExampleTest.php on line 65

/Users/lancer/Downloads/soft-mocks-master/src/QA/SoftMocks.php:1160
/Users/lancer/Downloads/soft-mocks-master/example-phpunit/ExampleTest.php:65

--

There were 4 failures:

1) ExampleTest::testFunction
Failed asserting that 1 matches expected 2.

/Users/lancer/Downloads/soft-mocks-master/example-phpunit/ExampleTest.php:33

2) ExampleTest::testConstant
Failed asserting that 3 matches expected 4.

/Users/lancer/Downloads/soft-mocks-master/example-phpunit/ExampleTest.php:40

3) ExampleTest::testClassConstant
Failed asserting that 5 matches expected 6.

/Users/lancer/Downloads/soft-mocks-master/example-phpunit/ExampleTest.php:46

4) ExampleTest::testMethod
Failed asserting that 24 matches expected -1.

/Users/lancer/Downloads/soft-mocks-master/example-phpunit/ExampleTest.php:52

ERRORS!
Tests: 5, Assertions: 4, Errors: 1, Failures: 4.

**Comment by Sannis** [comment]
@lancerhe, we will publish 7.1-compatible version soon.

**Comment by mougrim** [comment]
@lancerhe, could you check it?
We added php7.1 support in [1.3.0](https://github.com/badoo/soft-mocks/blob/master/CHANGELOG.md#v130) version.

**Comment by lancerhe** [comment]
See result, there is something wrong.

➜  soft-mocks-master phpunit example-phpunit/ExampleTest.php --bootstrap example-phpunit/bootstrap.php
PHPUnit 6.3.1 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.8
Configuration: /Users/lancer/soft-mocks-master/phpunit.xml

FFFFF                                                               5 / 5 (100%)

Time: 170 ms, Memory: 16.00MB

There were 5 failures:

1) ExampleTest::testFunction
Failed asserting that 1 matches expected 2.

/Users/lancer/soft-mocks-master/example-phpunit/ExampleTest.php:33

2) ExampleTest::testConstant
Failed asserting that 3 matches expected 4.

/Users/lancer/soft-mocks-master/example-phpunit/ExampleTest.php:40

3) ExampleTest::testClassConstant
Failed asserting that 5 matches expected 6.

/Users/lancer/soft-mocks-master/example-phpunit/ExampleTest.php:46

4) ExampleTest::testMethod
Failed asserting that 24 matches expected -1.

/Users/lancer/soft-mocks-master/example-phpunit/ExampleTest.php:52

5) ExampleTest::testGenerator
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => 3
-    1 => 4
-    2 => 5
+    0 => 1
+    1 => 2

/Users/lancer/soft-mocks-master/example-phpunit/ExampleTest.php:69

FAILURES!
Tests: 5, Assertions: 5, Failures: 5.

**Comment by mougrim** [comment]
@lancerhe looks like you didn't patch phpunit, see [Using with PHPUnit](https://github.com/badoo/soft-mocks#using-with-phpunit) instructions. Also, if didn't install phpunit through composer, you should require [bootstrap](https://github.com/badoo/soft-mocks/blob/master/src/bootstrap.php). Or write your own bootstrap with require your autoloader through soft mocks.

For my installation through composer it works:
```sh
$ php7.1 vendor/bin/phpunit example-phpunit/ExampleTest.php --bootstrap example-phpunit/bootstrap.php
PHPUnit 5.7.22 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.10-1+ubuntu16.04.1+deb.sury.org+1 with Xdebug 2.5.5
Configuration: /home/mougrim/Private/development/badoo/soft-mocks/phpunit.xml

.....                                                               5 / 5 (100%)

Time: 86 ms, Memory: 8.00MB

OK (5 tests, 6 assertions)
```

**Comment by lancerhe** [comment]
@mougrim 
Thanks, I see the patch.

Pass.
