### ISSUE TITLE
I installed the package by composer,but it couldn't include by composer? 

### ISSUE THREAD

**Issue by zhushengwen** [badoo/soft-mocks#36]
When debugging into composer,I found the composer.json not including “autoload” config! Is there any wrong?

**Comment by mougrim** [comment]
@zhushengwen, could you provide more details, for example, do you use phpunit?
If not how you require `vendor/autoload.php`.
Also could you provide soft-mocks install-log though composer?

**Comment by zhushengwen** [comment]
@mougrim, I use composer to install soft-mocks,and php frameworks is Yii2,then I use the code below.
`    public  function actionTest()
    {
        \Badoo\SoftMocks::setRewriteInternal(true);
        \Badoo\SoftMocks::redefineFunction(
            'strlen',
            '$a',
            'return \\Badoo\\SoftMocks::callOriginal("strlen", [trim($a)]));'
        );

        echo strlen('  aaa888   ').PHP_EOL;
    }`

`PHP Fatal error:  Class 'Badoo\SoftMocks' not found in /data/www/projects/yii2/console/controllers/MeController.php on line 121
PHP Stack trace:
PHP   1. {main}() /data/www/projects/yii2/yii:0
PHP   2. yii\base\Application->run() /data/www/projects/yii2/yii:23
PHP   3. yii\console\Application->handleRequest($request = class yii\console\Request { private $_params = array (0 => 'me/test'); private ${yii\base\Request}:_scriptFile = NULL; private ${yii\base\Request}:_isConsoleRequest = NULL; private ${yii\base\Component}:_events = array (); private ${yii\base\Component}:_eventWildcards = array (); private ${yii\base\Component}:_behaviors = NULL }) /data/www/projects/yii2/vendor/yiisoft/yii2/base/Application.php:386
PHP   4. yii\console\Application->runAction($route = 'me/test', $params = array ()) /data/www/projects/yii2/vendor/yiisoft/yii2/console/Application.php:147
PHP   5. yii\base\Module->runAction($route = 'me/test', $params = array ()) /data/www/projects/yii2/vendor/yiisoft/yii2/console/Application.php:180
PHP   6. yii\console\Controller->runAction($id = 'test', $params = array ()) /data/www/projects/yii2/vendor/yiisoft/yii2/base/Module.php:528
PHP   7. yii\base\Controller->runAction($id = 'test', $params = array ()) /data/www/projects/yii2/vendor/yiisoft/yii2/console/Controller.php:148
PHP   8. yii\base\InlineAction->runWithParams($params = array ()) /data/www/projects/yii2/vendor/yiisoft/yii2/base/Controller.php:157
PHP   9. call_user_func_array:{/data/www/projects/yii2/vendor/yiisoft/yii2/base/InlineAction.php:57}(array (0 => class console\controllers\MeController { private $cloudSetting = NULL; public $interactive = TRUE; public $color = NULL; public $help = NULL; private ${yii\console\Controller}:_passedOptions = array (...); private ${yii\console\Controller}:_reflections = array (...); public $id = 'me'; public $module = class yii\console\Application { ... }; public $defaultAction = 'index'; public $layout = NULL; public $action = class yii\base\InlineAction { ... }; private ${yii\base\Controller}:_view = NULL; private ${yii\base\Controller}:_viewPath = NULL; private ${yii\base\Component}:_events = array (...); private ${yii\base\Component}:_eventWildcards = array (...); private ${yii\base\Component}:_behaviors = array (...) }, 1 => 'actionTest'), array ()) /data/www/projects/yii2/vendor/yiisoft/yii2/base/InlineAction.php:57
PHP  10. console\controllers\MeController->actionTest() /data/www/projects/yii2/vendor/yiisoft/yii2/base/InlineAction.php:57
PHP Fatal Error 'yii\base\ErrorException' with message 'Class 'Badoo\SoftMocks' not found'

in /data/www/projects/yii2/console/controllers/MeController.php:121

Stack trace:
#0 /data/www/projects/yii2/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/data/www/projects/yii2/vendor/yiisoft/yii2/base/InlineAction.php:57}('array (0 => cla...', 'array ()')
#1 /data/www/projects/yii2/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams('array ()')
#2 /data/www/projects/yii2/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction(''test'', 'array ()')
#3 /data/www/projects/yii2/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction(''test'', 'array ()')
#4 /data/www/projects/yii2/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction(''me/test'', 'array ()')
#5 /data/www/projects/yii2/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction(''me/test'', 'array ()')
#6 /data/www/projects/yii2/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest('class yii\\conso...')
#7 /data/www/projects/yii2/yii(23): yii\base\Application->run()
#8 {main}
-bash: echo: write error: No space left on device`

**Comment by mougrim** [comment]
@zhushengwen, looks like you run tests not through vendor/bin/phpunit.
So you should modify your run script, you can details in [Usage](https://github.com/badoo/soft-mocks#usage) in readme:
> The thing that sets SoftMocks apart (and also limits their usage) is that they need to be **initiated** at the **earliest phase** of the app launch.

**Comment by mougrim** [comment]
Close, because there is no answer for long time.
