### ISSUE TITLE
I run the code as you mentioned,but the result is still original?

### ISSUE THREAD

**Issue by zhushengwen** [badoo/soft-mocks#37]
\Badoo\SoftMocks::setRewriteInternal(true);
        \Badoo\SoftMocks::redefineFunction(
            'strlen',
            '$a',
            'return \\Badoo\\SoftMocks::callOriginal("strlen", [trim($a)]));'
        );

        echo strlen('  aaa888   ').PHP_EOL;

![image](https://user-images.githubusercontent.com/5299147/44759434-bf5a8b80-ab6c-11e8-8f07-8e3f7c82f6fd.png)

**Comment by mougrim** [comment]
@zhushengwen, is your script required though soft-mocks (or script which require your script required through soft-mocks)? Also is autoloader required though soft-mocks?
See [usage](https://github.com/mougrim/soft-mocks#usage), how to require autoloader and others.

You can try SOFT_MOCKS_DEBUG environment variable:
```bash
SOFT_MOCKS_DEBUG=1 php path/to/your/base/script.php
```

**Comment by mougrim** [comment]
Close, because there is no answer for long time.
