### ISSUE TITLE
PHP Fatal error:  Call to undefined method QA\SoftMocksPrinter::pScalar_EncapsedStringPart()

### ISSUE THREAD

**Issue by RogulinSV** [badoo/soft-mocks#8]
Hi! (and sorry for my english)

We have found an error: 

> PHP Fatal error:  Call to undefined method QA\SoftMocksPrinter::pScalar_EncapsedStringPart() in vendor/badoo/soft-mocks/src/QA/SoftMocks.php on line 94

The code in our source file, causing an error:

``` php
$str = "Hello {$user['name']}";
```

Seems some method must be implemented in class QA\SoftMocksPrinter (or hi`s parent PhpParser\PrettyPrinter\Standard) for that issue:

``` php
protected function pScalar_EncapsedStringPart(\PhpParser\Node\Scalar\EncapsedStringPart $node)
{
    return '{' . $node->value . '}';
}
```

(not sure that`s code is correct)

**Comment by YuriyNasretdinov** [comment]
The thing is that in our version of PHP-Parser the code you supplied does not cause any parse errors. So I will just supply PHP-Parser version that Soft Mocks uses instead

**Comment by YuriyNasretdinov** [comment]
I updated bootstrap.php example so that it uses vendored version of PHP-Parser instead. Could you please check that it works now?

**Comment by YuriyNasretdinov** [comment]
Vendored version should work, so I close this issue. If there is anything that does not work, please create new one
